default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sandbox_rails6_development

test:
  <<: *default
  database: sandbox_rails6_test

production:
  <<: *default
  database: sandbox_rails6_production
